baseURL: "https://shahabrasekh.github.io/"
title: Shahab Rasekh's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
defaultContentLanguage: fa

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  fa:
    languagedirection: rtl
    title: Shahab's Blog
   # weight: 10

params:
  env: production  # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ø´Ù‡Ø§Ø¨ Ø±Ø§Ø³Ø®
  description: Ø¯Ø± Ø±Ø§Ø³ØªØ§ÛŒ ØªÙˆØ³Ø¹Ù‡
  keywords: [Blog, Portfolio, PaperMod, Ø´Ù‡Ø§Ø¨ Ø±Ø§Ø³Ø® , ØªÙˆØ³Ø¹Ù‡ Ú©Ø³Ø¨ Ùˆ Ú©Ø§Ø± ]
  author: Ø´Ù‡Ø§Ø¨ Ø±Ø§Ø³Ø®
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  defaultContentLanguage: fa
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "https://favicon.s3.ir-thr-at1.arvanstorage.com/favicon.ico"
    favicon16x16: "https://favicon.s3.ir-thr-at1.arvanstorage.com/favicon-16x16.png"
    favicon32x32: "https://favicon.s3.ir-thr-at1.arvanstorage.com/favicon-32x32.png"
    apple_touch_icon: "https://favicon.s3.ir-thr-at1.arvanstorage.com/apple-touch-icon.png"
    #safari_pinned_tab: "/"

  label:
    text: "Ø´Ù‡Ø§Ø¨ Ø±Ø§Ø³Ø®"
   # icon:
   # iconHeight: 35


# home-info mode

  homeInfoParams:
    Title: "ØªÙ„Ø§Ø´ÛŒ Ø¨Ø±Ø§ÛŒ ØªÙˆØ³Ø¹Ù‡ Ø®ÙˆØ¯Ù…"
    Content: | 
     Ù…Ø¯ÛŒØ± Ø¹Ù…Ù„ÛŒØ§ØªÛŒ Ø¹Ù„Ø§Ù‚Ù‡ Ù…Ù†Ø¯ Ø¨Ù‡ Ø³Ø§Ø²Ù…Ø§Ù†Ø¯Ù‡ÛŒ Ùˆ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø±ÛŒØ²ÛŒØŒ Ù…ØªØ¹Ù‡Ø¯ Ø¨Ù‡ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² Ø§Ø¨Ø²Ø§Ø±Ù‡Ø§ Ùˆ ØªÚ©Ù†ÙˆÙ„ÙˆÚ˜ÛŒ Ù†ÙˆÛŒÙ† ğŸ’¾ Ø¯Ø± Ú©Ø§Ø±Ù‡Ø§ÛŒ Ø±ÙˆØ²Ø§Ù†Ù‡.  Ø§Ø² Ø³Ø§Ù„ Û±Û³Û¹Û¸ Ø¯Ø± Ù…ÙˆØ±Ø¯ Ú©Ø§Ø±Ù‡Ø§ Ùˆ ÙØ¹Ø§Ù„ÛŒØªÙ… Ù…ÛŒ Ù†ÙˆÛŒØ³Ù… âœğŸ». ØªØ§ Ù‡Ù… Ø¨Ù‡ Ø®ÙˆØ¯Ù… Ù…ØªØ¹Ù‡Ø¯ Ø¨Ø§Ø´Ù… Ùˆ Ù‡Ù… Ø§Ø¬ØªÙ…Ø§Ø¹ÛŒ Ú©Ù‡ Ø¯Ø± Ø¢Ù† Ø²Ù†Ø¯Ú¯ÛŒ Ù…ÛŒÚ©Ù†Ù… !
  
  socialIcons:
    - name: twitter
      url: "https://twitter.com/rasekh_shahab"
    - name: instagram
      url: "https://instagram.com/shahab_rasekh"
    - name: github
      url: "https://github.com/shahabrasekh"
    - name: linkedin
      url: "https://www.linkedin.com/in/shahabrasekh/"
    - name: email
      url: "mailto:shahab.rasekh@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

#  editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
   # appendFilePath: true # to append file path to Edit link

   #for search
   #https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
#    - identifier: categories
 #     name: Ø¯Ø³ØªÙ‡ Ù‡Ø§
#      url: /categories/
 #     weight: 10
#    - identifier: posts
#     name: Ù†ÙˆØ´ØªÙ‡ Ù‡Ø§
#      url: /posts
#      weight: 5
 #   - identifier: tags
 #    name: Ø¨Ø±Ú†Ø³Ø¨ Ù‡Ø§
 #   url: /tags/
 #     weight: 20
#    - identifier: projects
#      name: Ù¾Ø±ÙˆÚ˜Ù‡ Ù‡Ø§
#      url: /project/
#      weight: 40
    - identifier: now
      name: Ø§Ú©Ù†ÙˆÙ†
      url: /now/
      weight: 30
    - identifier: archive
      name: Ø¬Ø³ØªØ¬Ùˆ
      url: /archives/
      weight: 50

# for a search page
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
